### ISSUE TITLE
2nd Layer skin

### ISSUE THREAD

**Issue by flodlol** [KallelGaNewk/mcdata#1]
Is there a way to get the 2nd layer visible?
<img width="258" alt="image" src="https://user-images.githubusercontent.com/60550710/101992414-55ba0900-3cb3-11eb-88d7-7e7ab7e52b79.png">

**Comment by KallelGaNewk** [comment]
Have you tried using `await mcdata.playerStatus('nickname', { skinOverlay: true })`?
If your problem persists, open a new issue.
