### ISSUE TITLE
URLs to player skin resources are changed

### ISSUE THREAD

**Issue by ShreshthTiwari** [KallelGaNewk/mcdata#7]
Please update the URLs

**Comment by KallelGaNewk** [comment]
not working anymore:
https://mc-heads.net/cape/
https://mc-heads.net/json/mc_status
https://api.mojang.com/user/profiles/UUID/names

**Comment by KallelGaNewk** [comment]
Update MCData and update your package: `npm i mcdata@1.1.0`

**Comment by ShreshthTiwari** [comment]
Thank you <3

**Comment by ShreshthTiwari** [comment]
.mojangStatus() is also not working ;/

**Comment by ShreshthTiwari** [comment]
https://mc-heads.net/json/mc_status

**Comment by ShreshthTiwari** [comment]
Also in
.playerStatus()
the name history is only showing the latest name

**Comment by KallelGaNewk** [comment]
> .mojangStatus() is also not working ;/

> https://mc-heads.net/json/mc_status

this endpoint from mc-heads now returns 404, not working anymore.
the original API from Mojang for status is also not working, see this: [WEB-2303](https://bugs.mojang.com/browse/WEB-2303?focusedCommentId=1086543&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1086543)
and i didn't find any other api for that, so i removed `.mojandStatus()`

**Comment by KallelGaNewk** [comment]
> Also in .playerStatus() the name history is only showing the latest name

Mojang said: "As of September 13th, we have removed public access to Minecraft’s Username History API endpoint to improve the player experience."
Read: [Username History API Removal FAQ](https://help.minecraft.net/hc/en-us/articles/8969841895693-Username-History-API-Removal-FAQ)

that means the name history doesn't exists anymore in Mojang's API

**Comment by KallelGaNewk** [comment]
If you find others APIs for that, feel free to open other issue
