### ISSUE TITLE
Issue with "axios" import

### ISSUE THREAD

**Issue by emberglazee** [KallelGaNewk/mcdata#8]
error happens when i try to start my script (`axios@1.1.3`):
```
...\node_modules\mcdata\mcdata.js:9
const { get } = require('axios').default;
        ^

TypeError: Cannot destructure property 'get' of 'require(...).default' as it is undefined.
```
UPD: cannot recreate this issue on `axios@0.21.4`

**Comment by KallelGaNewk** [comment]
Should be fixed in the commit above, update MCData: `npm i mcdata@1.1.1`
